from abc import abstractmethod, ABC


class DatabaseBase(ABC):
    @abstractmethod
    async def get(self, key: str) -> str: ...
    @abstractmethod
    async def set(self, key: str, value: str): ...
    @abstractmethod
    async def delete(self, key: str): ...
    @abstractmethod
    async def exists(self, key: str) -> bool: ...
